# This is the main configuration file for the application.
# https://www.playframework.com/documentation/latest/ConfigFile
db.default.driver = org.postgresql.Driver
db.default.url = "jdbc:postgresql://localhost:5432/themisys"
db.default.username = "postgres"
db.default.password = "ofspain86"

# Optional: Flyway can use the same
flyway.url = ${db.default.url}
flyway.user = ${db.default.username}
flyway.password = ${db.default.password}
flyway.locations = ["filesystem:conf/db/migration"]
# Custom migration table name
flyway.table = "flyway_schema_backoffice_history"

db.default.migration.auto=true
db.default.migration.validateOnMigrate=true
db.default.migration.sqlMigrationPrefix="V"