include "application.conf"

aws.s3.accessKeyId = "DEV_ACCESS_KEY"
aws.s3.secretAccessKey = "DEV_SECRET_KEY"

####### TO RUN ###########
## sbt -Dconfig.resource=application.dev.conf run
####################################################