include "application.conf"



####### TO RUN ###########################################
## sbt dist
## ./bin/your-app -Dconfig.resource=application.prod.conf
####################################################